#!/usr/bin/env python3
"""Render a Markdown summary of one or more DiagForge `report.json` files.

Used by the diagforge-pr GitHub workflow to build the body of the PR
comment. Standalone so the workflow can pipe the output straight into
`gh pr comment --body-file -`. Reads JSON only; no diagforge dependency
required.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


def _confidence_badge(c: str) -> str:
    return {"low": "🟡", "medium": "🟠", "high": "🔴"}.get(c, "⚪")


def summarize(report_path: Path) -> str:
    blob = json.loads(report_path.read_text())
    lines: list[str] = []
    slug = report_path.parent.name
    trace = blob["input"]["trace_file"]
    lines.append(f"### `{slug}`")
    lines.append(
        f"_Trace `{Path(trace['path']).name}` · {trace.get('event_count', '?')} frames "
        f"· {trace.get('duration_us', 0) / 1000:.0f} ms duration_"
    )

    for analysis in blob.get("analyses", []):
        dtc = analysis["dtc"]
        desc = dtc.get("description") or ""
        lines.append("")
        lines.append(f"**{dtc['code']}** _({dtc['standard']})_ {desc}")
        hyps = analysis["diagnostic_result"]["hypotheses"]
        if hyps:
            top = hyps[0]
            lines.append(
                f"- {_confidence_badge(top['confidence'])} **Top hypothesis** "
                f"({top['confidence']}): {top['description']}"
            )
            if top.get("evidence"):
                lines.append(
                    "  - Evidence: " + "; ".join(f"`{ev}`" for ev in top["evidence"][:2])
                )
        for m in analysis.get("mitigation_matches", []):
            params = ", ".join(
                f"`{p['name']}={p['suggested_value']}`"
                for p in m.get("parameter_suggestions", [])
                if p.get("suggested_value") is not None
            )
            extras = f" ({params})" if params else ""
            lines.append(
                f"- 🛠 **Mitigation**: `{m['pattern_id']}` — {m['pattern_name']}{extras}"
            )

    cross = blob.get("cross_dtc_findings", [])
    if cross:
        lines.append("")
        lines.append("**Cross-DTC findings**")
        for c in cross:
            lines.append(
                f"- `{' / '.join(c['dtc_codes'])}` ({c['type']}) — {c['description']}"
            )

    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if not argv:
        print("usage: summarize_reports.py <report.json> [<report.json> ...]", file=sys.stderr)
        return 2

    parts: list[str] = ["## DiagForge PR analysis", ""]
    for arg in argv:
        path = Path(arg)
        if not path.is_file():
            print(f"warning: skipping missing {path}", file=sys.stderr)
            continue
        parts.append(summarize(path))
        parts.append("")

    parts.append("---")
    parts.append(
        "_Generated by `.github/workflows/diagforge-pr.yml`. "
        "Re-run by pushing a new commit that touches `examples/` or `traces/`._"
    )
    sys.stdout.write("\n".join(parts) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
