"""Unit tests for .github/scripts/summarize_reports.py — the PR comment renderer.

Imported from the .github/scripts directory by path because it lives
outside the package on purpose (zero-dependency standalone script).
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / ".github" / "scripts" / "summarize_reports.py"

_spec = importlib.util.spec_from_file_location("summarize_reports", SCRIPT)
assert _spec and _spec.loader
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)
summarize = _mod.summarize


def _write_report(tmp_path: Path, *, slug: str, with_cross: bool = False) -> Path:
    dir_ = tmp_path / slug
    dir_.mkdir()
    report = {
        "report_id": "01890c1d-e000-7000-8000-aaaabbbbcccc",
        "schema_version": "1.0.0",
        "created_at": "2026-05-25T00:00:00Z",
        "tool": {"name": "diagforge", "version": "0.2.0"},
        "input": {
            "trace_file": {
                "path": "examples/foo/trace.asc",
                "format": "asc",
                "sha256": "a" * 64,
                "event_count": 94,
                "duration_us": 960_000,
            },
            "dtc_file": {"path": "dtcs.json", "sha256": "a" * 64, "dtc_count": 1},
        },
        "analyses": [
            {
                "dtc": {
                    "code": "P0300",
                    "standard": "obd2",
                    "description": "Random/Multiple Cylinder Misfire",
                    "occurrence_count": 1,
                },
                "pattern_features": {"window_us": 500_000, "notable_findings": ["finding"]},
                "diagnostic_result": {
                    "hypotheses": [
                        {
                            "rank": 1,
                            "description": "Insufficient dematuration",
                            "confidence": "high",
                            "evidence": ["finding"],
                            "suggested_pattern_id": "dematuration_timer",
                            "reasoning": "r",
                        }
                    ],
                    "model": "claude-opus-4-7",
                    "model_version": "claude-opus-4-7",
                    "prompt_template_version": "diag-v1",
                },
                "mitigation_matches": [
                    {
                        "pattern_id": "dematuration_timer",
                        "pattern_name": "Dematuration / fault-clear timer",
                        "parameter_suggestions": [
                            {
                                "name": "dematuration_time_ms",
                                "suggested_value": 1500,
                                "rationale": "r",
                            },
                            {
                                "name": "clear_threshold_offset",
                                "suggested_value": None,
                                "rationale": "r",
                            },
                        ],
                        "verification_steps": [],
                        "standards_references": [],
                    }
                ],
            }
        ],
        "cross_dtc_findings": (
            [
                {
                    "type": "co_occurring",
                    "dtc_codes": ["P0300", "P0301"],
                    "description": "both set within 50ms",
                    "delta_us": 50_000,
                }
            ]
            if with_cross
            else []
        ),
    }
    path = dir_ / "report.json"
    path.write_text(json.dumps(report))
    return path


def test_summarize_includes_top_hypothesis_and_mitigation(tmp_path: Path) -> None:
    path = _write_report(tmp_path, slug="p0300_intermittent_misfire")
    md = summarize(path)
    assert "### `p0300_intermittent_misfire`" in md
    assert "P0300" in md
    assert "Insufficient dematuration" in md
    assert "dematuration_timer" in md
    assert "dematuration_time_ms=1500" in md
    # Null parameter values are skipped from the inline list.
    assert "clear_threshold_offset" not in md


def test_summarize_includes_cross_dtc(tmp_path: Path) -> None:
    path = _write_report(tmp_path, slug="multi", with_cross=True)
    md = summarize(path)
    assert "Cross-DTC findings" in md
    assert "P0300 / P0301" in md


def test_main_writes_header_and_footer(tmp_path: Path, capsys) -> None:  # type: ignore[no-untyped-def]
    p = _write_report(tmp_path, slug="p0300_intermittent_misfire")
    rc = _mod.main([str(p)])
    out = capsys.readouterr().out
    assert rc == 0
    assert out.startswith("## DiagForge PR analysis")
    assert "Generated by" in out


def test_main_no_args_exits_usage(capsys) -> None:  # type: ignore[no-untyped-def]
    rc = _mod.main([])
    err = capsys.readouterr().err
    assert rc == 2
    assert "usage" in err
